### ISSUE TITLE
No Wire.beginTransmission() or Wire.endTransmission() needed for Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [Seeed-Studio/Seeed_Arduino_ADXL345#2]
The Wire.requestFrom() should not have a Wire.beginTransmission() or Wire.endTransmission(). They are only needed when writing data to a I2C Slave. The Wire.requestFrom() is a complete I2C transaction on its own.

**Comment by lanselambor** [comment]
@Koepel thank you for digging it out.

**Comment by KillingJacky** [comment]
Hi @Koepel , thanks for your percipience. If you like, could you please commit your patch for this driver with a pull-request? That prevents us reinvent the wheel and would be pretty appreciated.
